name: CD
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build-storybook
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PLURALSH_DESIGN }}'
          channelId: live
          projectId: pluralsh-design
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git config --global user.email "dherault@gmail.com" && git config --global user.name "David Hérault"
      - run: npm ci
      # Note: include tests here
      - run: npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      # The prepublishOnly script will run the build
      - run: npm version minor && npm publish
      # npm version creates a tag and a commit, let's push it
      - run: git pull && git push
