name: CI
on: pull_request
jobs:
  version:
    name: Check version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: check
        uses: EndBug/version-check@v1
        with:
          diff-search: true
          file-url: https://unpkg.com/pluralsh-design-system@latest/package.json
          static-checking: localIsNew
      - name: Log when unchanged
        if: steps.check.outputs.changed == 'false'
        run: 'echo "Update version in package.json"'
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - run: |
          yarn install --immutable
      - run: yarn build
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - run: |
          yarn install --immutable
      - run: yarn lint
  preview:
    name: Create preview
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - run: |
          yarn install --immutable
      - run: yarn build:storybook
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PLURALSH_DESIGN }}'
          projectId: pluralsh-design
